"""v2_added_expexted_op_field

Revision ID: 18b1ea0d0351
Revises: 494b2680c007
Create Date: 2024-10-02 16:10:06.054954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18b1ea0d0351'
down_revision: Union[str, None] = '494b2680c007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('expected_output', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'expected_output')
    # ### end Alembic commands ###
