"""v2_3

Revision ID: e2f024e203a0
Revises: 18b1ea0d0351
Create Date: 2024-10-03 15:53:13.740274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e2f024e203a0'
down_revision: Union[str, None] = '18b1ea0d0351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'topic')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('topic', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
